#!/bin/bash
set -ex

gcc=x86_64-w64-mingw32-gcc
gccar=x86_64-w64-mingw32-gcc-ar

$gcc -fpic -c -o hook1.o hook1.s
$gcc -fpic -c -o hook2.o hook2.s
$gcc -fpic -c -o hook3.o hook3.s
$gcc -g -c -fpic -O3 -o patcher.o patcher.c

$gcc -g -shared -o libpatcher.dll hook1.o hook2.o hook3.o patcher.o -Wl,--out-implib,libpatcher.dll.lib
