#!/bin/bash
set -ex

gcc -fpic -c -o hook1.o hook1.s
gcc -fpic -c -o hook2.o hook2.s
gcc -fpic -c -o hook3.o hook3.s
# gcc -fpic -c -g -o replacement.o replacement.s
gcc -g -c -fpic -O3 -o patcher.o patcher.c

gcc-ar rcs libpatcher.a patcher.o hook1.o hook2.o hook3.o
gcc -g -shared -o libpatcher.so patcher.o hook1.o hook2.o hook3.o

# LIBRARY_PATH=. gcc -o target -g target.c -lpatchme
