#!/bin/bash
set -ex

mkdir -p _build out

gcc=x86_64-w64-mingw32-gcc
gccar=x86_64-w64-mingw32-gcc-ar

$gcc -fpic -c -o _build/hook1.o windows/hook1.s
$gcc -fpic -c -o _build/hook2.o windows/hook2.s
$gcc -fpic -c -o _build/hook3.o windows/hook3.s
$gcc -fpic -c -o _build/hook4.o windows/hook4.s

$gcc -g -c -fpic -o _build/windows.o windows.c
$gcc -g -c -fpic -o _build/common.o common.c

$gcc -g -shared -o out/libpatcher.dll _build/{common.o,windows.o,hook1.o,hook2.o,hook3.o,hook4.o} -Wl,--out-implib,out/libpatcher.dll.lib
